### ISSUE TITLE
[bug] white screen at start-up

### ISSUE THREAD

**Issue by throwaway242685** [woheller69/huggingassist#11]
so, there's this white screen that pops-up when you're opening the app:

https://github.com/user-attachments/assets/773d267a-c7f0-4525-a15b-559d35837393

... even if you're using your phone on dark mode.

I've noticed the same issue on gptAssist.

perhaps you should make both apps detect if the phone's using dark mode or not? to prevent showing any white screen.

this white screen is kind of an issue for me (and my eyes, lol) when I open the app in the middle of the night :C

**Comment by woheller69** [comment]
the white screen appears when your phone is using day mode, a dark screen appears when phone in dark mode.
But then there is the theme you are setting inside the website. So when loading the page it will switch to the setting stored there. And that may be different

**Comment by woheller69** [comment]
Then is is probably a bug in your - old- Android

**Comment by throwaway242685** [comment]
it's not that old. :(

and I don't have this issue with other apps, so there should be a way to fix it here ;-;

**Comment by woheller69** [comment]
Android 9 does not support **automatic** handling of day / night mode.
Starts in Android 10
