### ISSUE TITLE
[bug] cited sources can't be opened

### ISSUE THREAD

**Issue by owosoup** [woheller69/huggingassist#12]
When using the "search web" function, the cited websites from the model are shown, but when clicked, nothing happens.

It would be nice to be able to open these:D. That's all

**Comment by woheller69** [comment]
it is the intention of this app to block all external URLs.
You can select the text of the link and share it to your favourite browser

**Comment by woheller69** [comment]
you can try this version. A long click on an URL will copy it to the clipboard and you can open it with your browser.
[app-release.apk.zip](https://github.com/user-attachments/files/16723788/app-release.apk.zip)

Uninstall
Remove .zip and install

**Comment by owosoup** [comment]
oh, ok! I'll try, thanks a bunch!

**Comment by owosoup** [comment]
It's not working very well, I think? Sorry I took a while. When I long-press a link (cited at the end of the AI's response) a popup says "downloading...", but nothing happens. Nothing is in my clipboard either. Maybe it's because I'm using FUTO keyboard, not Gboard?

**Comment by woheller69** [comment]
when you long click on an image it will download it. A long click on a normal URL will copy it and the popup says "copied"

**Comment by owosoup** [comment]
Ah, that's why. I was talking about those like you said: 
![Screenshot_2024-09-02-12-09-13-47_9a9e8e2b3fd4625881d599f7e0bf4bef](https://github.com/user-attachments/assets/8b5a7f85-fdc2-4b94-b2f8-497e8d19932b)
I don't really need to download the icons, plus they don't show up in the app anyway, they're just stored on my phone. So I have no way of getting the cited links! That's my complaint. But it's fine since I can go on the chat website to see.

**Comment by woheller69** [comment]
Try this:
[app-release.apk.zip](https://github.com/user-attachments/files/16836388/app-release.apk.zip)

**Comment by owosoup** [comment]
That works! It copies the URL. I don't need more, but for the sake of convenience, you could simply make it open into the default browser. Still, issue solved:)
