### ISSUE TITLE
Tools display lacks horizontal scrolling

### ISSUE THREAD

**Issue by Huge** [woheller69/huggingassist#14]
![Screenshot_20241003_061520_huggingAssist.jpg](https://github.com/user-attachments/assets/ca36c826-5da6-451b-9f9a-89d9bd9436ff)

currently impossible to read what I've activated/enabled

**Comment by woheller69** [comment]
I rather think that is a bug on their HuggingChat website
Your display seems to be extremely small. You can rotate your phone.
