### ISSUE TITLE
Please, remove "Reset" button or make it smaller

### ISSUE THREAD

**Issue by DanielProg39** [woheller69/huggingassist#2]
This rather ugly and merely useful (esp. given its size) button takes a pretty visible spot in the interface. If I want to sign out, there is corresponding button in web interface and if I want to reset the app, I can do it by deleting its data in system settings. If for some objective reason it needs to stay, it'd be better if it was similar to the small button in right corner that can be hidden, as it's done in gptAssist.

**Comment by woheller69** [comment]
Try this. The button is smaller and is deactivated/activated with swipe up/down

Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/huggingassist/files/13695704/app-release.apk.zip)

**Comment by DanielProg39** [comment]
That's much better, thanks for taking my idea into consideration :+1:
