### ISSUE TITLE
Name does not look well on F-droid

### ISSUE THREAD

**Issue by guysoft** [woheller69/huggingassist#3]
Thought you might like to know. 
![Screenshot_20231221_120039_F-Droid](https://github.com/woheller69/huggingassist/assets/325670/5d246833-1b08-4074-975b-2bf9ad9009b4)

![Screenshot_20231221_120050_F-Droid](https://github.com/woheller69/huggingassist/assets/325670/7c27a75f-9c66-48e2-8972-59915de1c91b)

**Comment by woheller69** [comment]
nothing I can change. Depends on screen size, etc
