### ISSUE TITLE
Line break enter acts as send enter

### ISSUE THREAD

**Issue by BluishHumility** [woheller69/huggingassist#4]
Hello,

I am running version 1.6 of huggingAssist, installed from F-Droid.

When writing a response, the OSK has a "send" button (seen here in the bottom right):

![Screenshot_20240211-184545](https://github.com/woheller69/huggingassist/assets/93340027/634c4fe8-9edb-46d4-8567-d647a5c75e9e)

When I press shift, it changes to a line break symbol:

![Screenshot_20240211-184558](https://github.com/woheller69/huggingassist/assets/93340027/d655452e-524b-47a2-9621-e94fc5f55d1e)

However, when I press it the message is sent instead of getting the line break.

![Screenshot_20240211-184610](https://github.com/woheller69/huggingassist/assets/93340027/54aa7785-85a2-4f68-a946-06ce04ef3189)

I have tried holding down shift as well. Apologies if this is a silly issue, I just cannot figure out how to add a line break.

**Comment by woheller69** [comment]
unfortunately shift return is not available on android. For the AI that does not matter anyway
