### ISSUE TITLE
Does not scroll all the way to the bottom

### ISSUE THREAD

**Issue by Feroszip** [woheller69/huggingassist#5]
The problem is that you cannot scroll down when selecting a model.
When selecting Create Assistant, it is also impossible to scroll down, you can see everything on the screenshots:
![Screenshot_2024-02-12-14-05-17-096_org woheller69 hugassist](https://github.com/woheller69/huggingassist/assets/92949095/2ffd79e9-cefe-4570-86b7-3a90efbf44f6)
![Screenshot_2024-02-12-14-05-23-984_org woheller69 hugassist](https://github.com/woheller69/huggingassist/assets/92949095/ca34d2b0-94ca-4c5a-80dd-291497925343)
Poco x3 nfc phone

**Comment by woheller69** [comment]
strange, I do not have this issue.

**Comment by p134c0d3** [comment]
I am on a Pixel 6a and can confirm that I do not have this issue on the latest release.

**Comment by woheller69** [comment]
obviously a device specific issue.
