### ISSUE TITLE
Upload file button does not work

### ISSUE THREAD

**Issue by mecuricat** [woheller69/huggingassist#6]
Using CohereForAI/c4ai-command-r-plus, an upload button is displayed on the bottom right corner.

<p align=center><img src="https://github.com/woheller69/huggingassist/assets/112750975/9553229d-f6da-4c1b-81c0-f731ed515886" width="250px"/></p>

But tapping on the button does nothing. Is this intended?

**Comment by woheller69** [comment]
It is not implemented. Will have a look at it next week

**Comment by woheller69** [comment]
Please try this version.
[app-release.apk.zip](https://github.com/user-attachments/files/15571268/app-release.apk.zip)

-Uninstall
-Remove .zip and install

**Comment by mecuricat** [comment]
I receive the following toast. No matter what I ask. I am not even sure whether the document has been uploaded or not. I also waited for 2 mins before asking anything. Same outcome.

<p align=center><img src="https://github.com/woheller69/huggingassist/assets/112750975/66ac9472-783a-439e-a253-7f1fbef9f412" width="250px"/></p>

**Comment by woheller69** [comment]
413 means content is too large

**Comment by mecuricat** [comment]
The file size shows 404 kB (403,598 bytes). How may I know whether a document has been uploaded successfully?

**Comment by woheller69** [comment]
I just uploaded a pdf with 8MB without problem
It shows the uploaded file as in your screenshot, just without the error message

**Comment by mecuricat** [comment]
Yes, I can see the document. But there was no message informing that the document had indeed uploaded successfully. Can you please show a message saying file uploaded successfully once it is so?

**Comment by woheller69** [comment]
this is the case if it is uploaded and there is no "Request failed..."
