### ISSUE TITLE
generated images and resource avatars are not loaded at all

### ISSUE THREAD

**Issue by Wjxfi** [woheller69/huggingassist#7]
Rlly

Poco x3 pro.

**Comment by woheller69** [comment]
![Screenshot_20240614-154931_huggingAssist](https://github.com/woheller69/huggingassist/assets/68678880/5980a070-28fc-4b98-a9d6-d3af0e92bbf7)

works...

**Comment by woheller69** [comment]
which model? Cohere?

**Comment by woheller69** [comment]
For privacy reasons this app blocks all URLs not coming from huggingface...

If you need that feature you can give up privacy and use Chrome...

**Comment by woheller69** [comment]
then these assistants use URLs from outside huggingface which this app does not allow...

**Comment by woheller69** [comment]
If just this one domain is needed, I can add it.

**Comment by woheller69** [comment]
please uninstall and try the apk from here
https://github.com/woheller69/huggingassist/actions/runs/9536343693/artifacts/1606112652

**Comment by woheller69** [comment]
I am getting a zip file

**Comment by woheller69** [comment]
[2024-06-16_-_woheller69_-__-_APK(s)_debug_generated.zip](https://github.com/user-attachments/files/15858187/2024-06-16_-_woheller69_-__-_APK.s._debug_generated.zip)

**Comment by woheller69** [comment]
I just added this one domain.
Hope it works

**Comment by woheller69** [comment]
so you need pollinations.ai instead of images.pollinations.ai ? Or what else?

**Comment by woheller69** [comment]
the subdomain is always included. So pollinations.ai is sufficient.
Please try:
[app-release.apk.zip](https://github.com/user-attachments/files/15889362/app-release.apk.zip)

**Comment by woheller69** [comment]
My fault. I thought subdomains were included but they were not. Now all subdomains are allowed.
Next week they may require pictures.polinations.ai or whatever...
[app-release.apk.zip](https://github.com/user-attachments/files/15890476/app-release.apk.zip)

**Comment by woheller69** [comment]
what exactly does not work?
I can create an image with image generator and I can also create an image from Cohere.
Maybe something was wrong with the apk. Here is an update:

[app-release.apk.zip](https://github.com/user-attachments/files/15897524/app-release.apk.zip)

If it does not work, please describe exactly how I can reproduce it.

**Comment by woheller69** [comment]
What is this. Send a description where you click

**Comment by woheller69** [comment]
These images have githubusercontent urls

**Comment by woheller69** [comment]
Which model? Dall-e?

**Comment by woheller69** [comment]
Should be fixed now:
[app-release.apk.zip](https://github.com/user-attachments/files/15899644/app-release.apk.zip)
